# -*- coding: utf-8 -*-
"""PhytonIntroduction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1riKZEZNotYnruGORXJwCalcpXFXE8jGK
"""

print('welcome aisyah to Pyhton')

print('do less get more')

print('10+5')

#input example
username=input ('Enter Username')
print('welcome to the world Mr./Mrs.:' + username)

num1=12
num2=25
result=num1+num2
print(result)

print(f'first number {num1} and secound number {num2} Result: {result}')

fnum= (input('enter first number'))
snum=(input('enter secound number'))
result=fnum+snum
print (f'Result after adding {fnum} and {snum} is =\t {result}')

fnum=int(input('enter first number'))
snum=int(input('enter secound number'))
result=fnum+snum
print (f'Result after adding {fnum} and {snum} is =\t {result}')

type({})

num=12
type(num)
print (f'{num}')
print(f'type of fnum {type(fnum)} and snum {type(snum)}')

my_num=12.44
type(my_num)

fnum=float(input('enter first number'))
snum=float(input('enter secound number'))
result=fnum+snum
print (f'Result after adding {fnum} and {snum} is =\t {result}')

#BOOLEAN OR BOOL
is_active=True
type(is_active)

is_active=False
type(is_active)

print(f'Is active User?, {is_active}')

print(f'Is active User?, is_active')

#Binary Values
byte_ex=b'hello'
type(byte_ex)

#complex type
complex_num=2+3j
print(complex_num)
type(complex_num)

#sequence type
#list[]
list_ex={1,2,3,4,5}
type(list_ex)

list_ex={1,2,3,4,5}
print(list_ex)
type(list_ex)

cars=['BMW,MINI COOPER,AUDI']
print(cars)
type(cars)

cars=['BMW,MINI COOPER,AUDI']
print(f'type of car is = {(cars)}')

#tuple
tuple_ex=(1,2,3,4,5)
print(tuple_ex)
type(tuple_ex)

#dictionary
emp={
    "id":1,
    "name":"Aisyah",
    "salary":20000.77

}
print(emp)
type(emp)

#set
set_ex={10,20,30,40,50}
print(set_ex)
type(set_ex)

#range
range_ex=range(10)
print(range_ex)
type(range_ex)

range_ex2=range(5,20)
print(range_ex2)
type(range_ex2)

